### ISSUE TITLE
terrestrial.xml should be reviewed

### ISSUE THREAD

**Issue by fabioganga** [oe-alliance/oe-alliance-tuxbox-common#114]
Hello,

The terrestrial.xml should take into consideration that the old UHF TV channel frequencies 49-69 are now being used for LTE services and are, as such, no longer transmitting TV signals.

These channels should be deleted from the list, therefore, as it only prolongs the TV scan time needlessly.

Thanks.

**Comment by Huevos** [comment]
Please send a pull request.

**Comment by AbuBaniaz** [comment]
Done here: https://github.com/oe-alliance/oe-alliance-tuxbox-common/commit/4ddf466b411f101c5a89b36c0afb2b6f19f3257a
