### ISSUE TITLE
How to push a commit here?

### ISSUE THREAD

**Issue by Lexzie** [oe-alliance/oe-alliance-tuxbox-common#117]
I made changes with Github Desktop yesterday and pushed them to the repository.
At least I thought I did (just like I do in other repositories).
But I don't see anything has changed here.
I changed the cables.xml I see you used my file from Sat4all, but it's not up-to-date here.

**Comment by Huevos** [comment]
You can't push to this repo unless you are a member, but, you can make a pull request.

No changes to satellites.xml. Only to Terrestrial.xml and Cables.xml.

**Comment by AbuBaniaz** [comment]
We did not use your file from `Sat4all`. 

All OE-A images and PLI use the name, not position on xml file. It has been like that for a number of years. We keep them in alphabetical order. You can ignore the `don't split the file`  that others say.

	Countries sorted by three letter country code (ISO 3166).
	Regions sorted alphabetically.

**Comment by AbuBaniaz** [comment]
We also use the space before closing bracket as some editors need them.

**Comment by Lexzie** [comment]
> We also use the space before closing bracket as some editors need them.

Then I will do that in my file too.
Is there a reason for using `flags="9"` ?

**Comment by Lexzie** [comment]
I understand that and why I can't push into this repository, but when making the changes I can do a push in Github Desktop to master branch.
I probably should have done it otherwise, but where did that push go??

I'm not that good in this, please help.

**Comment by AbuBaniaz** [comment]
You pushed to your fork/copy. You can submit pull request using the website.
