### ISSUE TITLE
Layout of cables.xml

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/oe-alliance-tuxbox-common#119]
When Huevos and I added the country code and all images were adapted to use the name instead of position in xml file,  we took the opportunity to tidy up the file. 

During the discussion at the time, someone mentioned that we should not use the name as these can change. There was no other suggestion/objection. It was agreed to keep the file ordered firstly by country code, then area names. Commenst to thsi effetc were added at the header of the file. The brute force ones were kept at the top. This obviously means that the in the all countries selection method, the names are not in an alphabetical order.  

I have re-ordered the file again. Are there any objections or valid reasons why we want to go back to pre 2019 method? 

And also, what are the rules about forum names being included in there?  I don't think we should list any. websites/repositories should be fine.

**Comment by AbuBaniaz** [comment]
@mike-99 
I'd be grateful for your feedback.

**Comment by Huevos** [comment]
Sort as per the current system.

I don't see any reason to include comments not related to this file, e.g. links to forums should be removed. Atribution is by commit author. If people want recognition in the file the commit should be refused.

Nothing wrong with using the names. They are unique, and anyway why would a name change?

**Comment by Lexzie** [comment]
The link/recognition was there already before I submitted the first time in 2022 and so I changed it again now. So, don't blame me.

**Comment by Lexzie** [comment]
> I don't see any reason to include comments not related to this file, e.g. links to forums should be removed. Atribution is by commit author. If people want recognition in the file the commit should be refused.

What I was trying to say is that if the comment in the file is not allowed delete it, but please don't refuse (the rest of) my PR.

**Comment by AbuBaniaz** [comment]
There is no blame being apportioned to anyone.  It is just so that we agree a method so we are all working to one method. No point me changing it to one way and somebody else doing it another way. Ultimately, the machine code will do the sorting, but file has to have some structure. 

@Lexzie 
Your pull request was merged.

**Comment by Lexzie** [comment]
I would say order it by first no country (CableBruteforce listst f.e.), then alphabetical on countrycode and per countrycode alphabetical for providername.

Edit: I see you have done that. 👍🏻 

Look at the Austrian network LIWEST is that layout okay?

**Comment by AbuBaniaz** [comment]
There was a space tab anomaly, I have converted the ones you pointed out. I am sure those with scripts to automate the process can give it a once over.
