### ISSUE TITLE
Please add  China DTMB Terrestrial  frequency

### ISSUE THREAD

**Issue by xxj737** [oe-alliance/oe-alliance-tuxbox-common#124]
DTMB（GB 20600-2006， Digital Terrestrial Multimedia Broadcast，），DMB-T/H（Digital Multimedia Broadcast-Terrestrial/Handheld，
Digital multimedia broadcasting (terrestrial/handheld) is a standard for digital video broadcasting in China, formulated by the People's Republic of China for digital television and mobile digital broadcasting. This format will serve half of China's television viewers, especially in suburban and rural areas. DTMB is currently used in Chinese Mainland, Hong Kong, Macao and Cuba.

DTMB      Bandwidth= 8MHZ 

[
[DTMB.txt](https://github.com/oe-alliance/oe-alliance-tuxbox-common/files/15104889/DTMB.txt)
](url)
</terrestrial>
	<terrestrial name="China (China DTMB)" flags="1" countrycode="CHN">
		<transponder centre_frequency="525000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="605000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="685000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="080000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="088000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="171000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="179000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="187000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="195000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="203000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="211000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="219000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="474000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="482000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="490000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="498000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="506000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="514000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="522000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="530000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="538000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="546000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="554000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="562000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="570000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="578000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="586000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="594000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="602000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="610000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="618000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="626000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="634000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="642000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="650000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="658000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="666000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="674000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="682000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="690000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="698000000" bandwidth="0" constellation="3" system="0" />

**Comment by xxj737** [comment]
`</terrestrial>
	<terrestrial name="China (China DTMB)" flags="1" countrycode="CHN">
		<transponder centre_frequency="525000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="605000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="685000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="080000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="088000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="171000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="179000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="187000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="195000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="203000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="211000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="219000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="474000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="482000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="490000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="498000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="506000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="514000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="522000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="530000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="538000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="546000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="554000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="562000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="570000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="578000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="586000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="594000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="602000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="610000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="618000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="626000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="634000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="642000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="650000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="658000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="666000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="674000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="682000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="690000000" bandwidth="0" constellation="3" system="0" /> 
		<transponder centre_frequency="698000000" bandwidth="0" constellation="3" system="0" /> `

**Comment by xxj737** [comment]
DTMB National Standard Modulator General Administration 7 Recommended Modes

1 C=3780 16QAM 0.4 PN=945 720  

2 C=1 4QAM 0.8 PN=595 720  

3 C=3780 16QAM 0.6 PN=945 720 

4 C=1 16QAM 0.8 PN=595 720 

5 C=3780 16QAM 0.8 PN=420 720  

6 C=3780 64QAM 0.6 PN=420 720  

7 C=1 32QAM 0.8 PN=595 720  

 
![d4a5a6cadbef4ffdbaaa6b2bf4725eda](https://github.com/oe-alliance/oe-alliance-tuxbox-common/assets/50125219/2be188df-3059-48fc-9da4-55d6bb683395)

**Comment by Huevos** [comment]
This doesn't appear to be in order...

**Comment by xxj737** [comment]
DTMB  Bandwidth= 8MHz

![554](https://github.com/oe-alliance/oe-alliance-tuxbox-common/assets/50125219/f1915295-c7de-420b-a494-b53405269b29)

**Comment by Huevos** [comment]
Your transponders need to be in order from lowest frequency ascending, like all the other entries in the file.

**Comment by Huevos** [comment]
Also this: `centre_frequency="080000000" `, does such a low frequency exist for TV channels?

**Comment by xxj737** [comment]
China plans to have VHF in the ground frequency band
But it hasn't started to be activated yet
UHF is already enabled

**Comment by xxj737** [comment]
Will be used in the  52.5MHz-219MHz
Now     47MHz------698MHz

**Comment by Huevos** [comment]
You have 522 and 525.
Also 682 and 685.

Those overlap.

**Comment by EnoSat** [comment]
<transponder centre_frequency="052500000" bandwidth="0" constellation="3" system="0" /> 
<transponder centre_frequency="060500000" bandwidth="0" constellation="3" system="0" /> 
<transponder centre_frequency="068500000" bandwidth="0" constellation="3" system="0" />

**Comment by xxj737** [comment]
> Also 682 and 685.

yes,You are correct
![QQ浏览器截图20240426070253](https://github.com/oe-alliance/oe-alliance-tuxbox-common/assets/50125219/521cee4d-1dc9-4d4b-8607-0883f31fdab0)

**Comment by Huevos** [comment]
https://github.com/oe-alliance/oe-alliance-tuxbox-common/commit/01fb99624bd8ff25a0e9a717d1ffa580b4c9e14c

**Comment by AbuBaniaz** [comment]
As these have been added, I will close the issue.

**Comment by xxj737** [comment]
OK,Thank you !
