### ISSUE TITLE
Hot

### ISSUE THREAD

**Issue by StaRipper** [oe-alliance/oe-alliance-tuxbox-common#73]
[cables.zip](https://github.com/oe-alliance/oe-alliance-tuxbox-common/files/3219300/cables.zip)

Please add to cables.xml:
			<cable name="HOT" satfeed="true" flags="9" countrycode="ISR">
       
      <transponder frequency="306000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="346000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="354000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="410000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="434000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="442000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="458000000" symbol_rate="6890000" fec_inner="5" modulation="5" />         
      <transponder frequency="466000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="474000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="482000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="490000000" symbol_rate="6890000" fec_inner="5" modulation="5" />   
      <transponder frequency="498000000" symbol_rate="6890000" fec_inner="5" modulation="5" />         
      <transponder frequency="538000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="546000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="554000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="562000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="570000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="578000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="586000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      <transponder frequency="594000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="618000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
      
      <transponder frequency="626000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
            
      <transponder frequency="642000000" symbol_rate="6890000" fec_inner="5" modulation="5" />
              
      <transponder frequency="650000000" symbol_rate="6890000" fec_inner="5" modulation="5" />      
      
      </cable>

**Comment by Huevos** [comment]
Please submit a pull request with a proper description of your changes.

**Comment by AbuBaniaz** [comment]
I have added the HOT provider.

I have also added some of the country codes your file had. Should you wish to do more, please esnure you submit changes against the most recent file.
