### ISSUE TITLE
Brazilian/South america terrestrial (ISDB-T) missing

### ISSUE THREAD

**Issue by frankviana** [oe-alliance/oe-alliance-tuxbox-common#89]
We need to add this 6MHZ frequencies:

[https://mega.nz/file/XcN3mCoQ#X8cOUkHy1K9bmkE6Q0y41YK50IAbp05uNGf9A83g_FA](url)

[https://www.mediafire.com/file/x6leyu70ypipdp7/terrestrial.xml/file](url)

<?xml version="1.0" encoding="iso-8859-1"?>

<locations>
<terrestrial name="Brazil ISDB-T Frequencies" flags="5">
<transponder centre_frequency="473142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="479142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="485142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="491142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="497142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="503142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="509142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="515142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="521142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="527142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="533142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="539142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="545142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="551142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="557142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="563142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="569142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="575142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="581142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="587142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="593142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="599142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="605142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="617142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="623142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="629142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="635142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="641142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="647142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="653142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="659142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="665142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="671142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="677142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="683142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="689142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="695142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="701142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="707142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="713142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="719142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="725142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="731142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="737142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="743142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="749142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="755142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="761142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="767142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="773142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="779142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="785142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="791142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="798142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="803142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
</terrestrial>
</locations>

**Comment by AbuBaniaz** [comment]
Those links do not work. Attach the file here directly. Better still submit a pull request.

**Comment by frankviana** [comment]
```
<?xml version="1.0" encoding="iso-8859-1"?>


<locations>
<terrestrial name="Brazil ISDB-T Frequencies" flags="5">
<transponder centre_frequency="473142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="479142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="485142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="491142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="497142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="503142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="509142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="515142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="521142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="527142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="533142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="539142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="545142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="551142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="557142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="563142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="569142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="575142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="581142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="587142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="593142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="599142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="605142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="617142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="623142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="629142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="635142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="641142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="647142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="653142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="659142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="665142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="671142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="677142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="683142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="689142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="695142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="701142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="707142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="713142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="719142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="725142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="731142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="737142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="743142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="749142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="755142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="761142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="767142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="773142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="779142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="785142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="791142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="798142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
<transponder centre_frequency="803142857" bandwidth="2" constellation="3" code_rate_hp="5" code_rate_lp="5" guard_interval="5" transmission_mode="2" hierarchy_information="4" inversion="2" system="0"/>
</terrestrial>
</locations>
```

**Comment by frankviana** [comment]
> Those links do not work. Attach the file here directly. Better still submit a pull request.

I don't know how to do pull request...

Posted here. Please add.
